baseURL = "https://skeletron.app/"
headerFontSize = 128
languageCode = "en-us"
publishDir = "/Users/anonnemacher/Sites/github/nonjo.github.io"
theme = "skeletron"
title = "skelesite"
[github]
[menu]
	[[menu.footer]]
		identifier = "about"
		name = "About"
		url = "/about/"
	[[menu.footer]]
		identifier = "manual"
		name = "Manual"
		url = "/manual"
[params]
	project_name = "Skeletron"
