baseURL = "https://nonjo.github.io"
headerFontSize = 128
languageCode = "en-us"
publishDir = "docs"
theme = "skeletron"
title = "gitblog"
[menu]
	[[menu.footer]]
		identifier = "about"
		name = "About"
		url = "/about/"
	[[menu.footer]]
		identifier = "manual"
		name = "Manual"
		url = "/manual"
[params]
	project_name = "Skeletron"
